# Numpy

# Practical Questions:

#  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [1]:
#Code
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T

print("\nTransposed array:")
print(transposed_arr)

Original array:
[[26 74 89]
 [44 50 88]
 [43 61 80]]

Transposed array:
[[26 44 43]
 [74 50 61]
 [89 88 80]]


# Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
#Code
import numpy as np

# Create a 1D array with 10 elements
arr = np.arange(10)

# Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)

print("2x5 array:")
print(arr_2x5)

# Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)

print("\n5x2 array:")
print(arr_5x2)

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
#Code
import numpy as np

# Create a 4x4 array with random float values
arr = np.random.rand(4, 4)

# Add a border of zeros
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr_with_border)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.90921461 0.15995547 0.41161549 0.71233187 0.        ]
 [0.         0.56333792 0.55800066 0.75006656 0.17791678 0.        ]
 [0.         0.41171501 0.12809082 0.29972228 0.58994739 0.        ]
 [0.         0.699154   0.31272682 0.22973848 0.06006916 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
#Code
import numpy as np

array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


#  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

In [7]:
#Code
import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations using a loop
upper_arr = []
lower_arr = []
title_arr = []

for word in arr:
    upper_arr.append(word.upper())
    lower_arr.append(word.lower())
    title_arr.append(word.title())

print("Uppercase:", upper_arr)
print("Lowercase:", lower_arr)
print("Title case:", title_arr)

Uppercase: ['PYTHON', 'NUMPY', 'PANDAS']
Lowercase: ['python', 'numpy', 'pandas']
Title case: ['Python', 'Numpy', 'Pandas']


#  Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [8]:
#Code
import numpy as np

words = np.array(["hello", "world", "numpy"])

# Create a function to insert spaces between characters
def insert_spaces(word):
    return " ".join(word)

# Apply the function to each word using vectorization
words_with_spaces = np.array(list(map(insert_spaces, words)))

print(words_with_spaces)

['h e l l o' 'w o r l d' 'n u m p y']


#  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [9]:
#Code
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
add_result = arr1 + arr2

# Element-wise subtraction
sub_result = arr1 - arr2

# Element-wise multiplication
mul_result = arr1 * arr2

# Element-wise division
div_result = arr1 / arr2

print("Addition:\n", add_result)
print("\nSubtraction:\n", sub_result)
print("\nMultiplication:\n", mul_result)
print("\nDivision:\n", div_result)

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Multiplication:
 [[ 5 12]
 [21 32]]

Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


#  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [10]:
#Code
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


#  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [11]:
#Code
import numpy as np

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

# Generate a NumPy array of 100 random integers
random_array = np.random.randint(0, 1001, 100)

# Find prime numbers using a list comprehension and the is_prime function
prime_numbers = [num for num in random_array if is_prime(num)]

print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [283, 647, 353, 271, 563, 137, 263, 599, 211, 613, 757, 739, 967, 991, 433, 491, 293]


#  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [13]:
#Code
import numpy as np

# Generate a NumPy array of 28 daily temperatures
temperatures = np.random.randint(15, 35, size=28)

# Reshape the array into a 4x7 array (4 weeks, 7 days/week)
weekly_temperatures = temperatures.reshape(4, 7)

# Calculate the average temperature for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Weekly Averages:")
print(weekly_averages)

Weekly Averages:
[22.42857143 24.         22.14285714 26.14285714]
